# Gateway Service
# Запуск: docker-compose up -d --scale gateway=2

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: ${EUREKA_URL:-http://discovery:8761/eureka/}
      KEYCLOAK_ADDRESS: ${KEYCLOAK_ADDRESS:-http://keycloak:8080}
    ports:
      - "8180-8185:8080"
    networks:
      - infra-network
    restart: unless-stopped

networks:
  infra-network:
    name: infra-network
    external: true
