spring:
  application:
    name: blockly-executor
  cloud:
    discovery:
      enabled: true
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    consumer:
      auto-offset-reset: earliest

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:true}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    contexts: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/blockly}
    username: ${SPRING_DATASOURCE_USERNAME:blockly}
    password: ${SPRING_DATASOURCE_PASSWORD:blocklypwd}
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 1
      minimum-idle: 1
      max-lifetime: 1800000
      idle-timeout: 600000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}


server:
  port: ${SERVER_PORT:8085}
blockly:
  kafka:
    topic: blockly-executor-procedures

kafka:
  topic:
    partitions: 12
