# Keycloak (требует postgres)
# Запуск: docker-compose up -d

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-blockly}
      KC_DB_USERNAME: ${POSTGRES_USER:-blockly}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD:-blocklypwd}
      KC_HOSTNAME: keycloak
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - infra-network
    restart: unless-stopped

networks:
  infra-network:
    name: infra-network
    external: true
